name: kita_46_2
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.0
  share_plus: ^9.0.0
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  google_sign_in: ^7.2.0
  cloud_firestore: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.0
  share_plus: ^9.0.0
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

# Konfigurasi ikon aplikasi (sejajar di kiri)
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/Merahldii.png"
  min_sdk_android: 21

# Konfigurasi khusus flutter (sejajar di kiri)
flutter:
  uses-material-design: true

  # Blok assets HARUS ada di dalam blok flutter, sejajar dengan uses-material-design
  assets:
    - "assets/Asmaul husna/asmaul_husna.json"
    - assets/surah/
    - assets/list_surah.json
    - assets/images/
    - "assets/PR 13/pr13.json"

  # FONT KITA LUPAKAN DULU BIAR GAK ERROR
  # fonts:
  #   - family: LPMQ
  #     fonts:
  #       - asset: assets/fonts/LPMQ.ttf