// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT2_JuEf1VgpmY0E878QZLuNAjES8xPxc',
    appId: '1:343296288430:web:72bc08750c667436576f3f',
    messagingSenderId: '343296288430',
    projectId: 'kita-46-2',
    authDomain: 'kita-46-2.firebaseapp.com',
    storageBucket: 'kita-46-2.firebasestorage.app',
    measurementId: 'G-KMN89N66H1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbuAJwhHY1mCgiqlmVGIaYT50AlTl2izU',
    appId: '1:343296288430:android:5402af121654556c576f3f',
    messagingSenderId: '343296288430',
    projectId: 'kita-46-2',
    storageBucket: 'kita-46-2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-FRF878x1FqRglHRXBdnPLY_OwhuzdFo',
    appId: '1:343296288430:ios:4a6f7948143bcc71576f3f',
    messagingSenderId: '343296288430',
    projectId: 'kita-46-2',
    storageBucket: 'kita-46-2.firebasestorage.app',
    iosBundleId: 'com.example.kita462',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDT2_JuEf1VgpmY0E878QZLuNAjES8xPxc',
    appId: '1:343296288430:web:12cb263a66195e85576f3f',
    messagingSenderId: '343296288430',
    projectId: 'kita-46-2',
    authDomain: 'kita-46-2.firebaseapp.com',
    storageBucket: 'kita-46-2.firebasestorage.app',
    measurementId: 'G-48TK000BXC',
  );
}
